# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Aritmatika.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QMainWindow, QLabel, QVBoxLayout, QWidget, QPushButton, QFileDialog
from PyQt5.QtGui import QPixmap

class ResultWindow(QMainWindow):
    def __init__(self, image):
        super().__init__()
        self.setWindowTitle("Hasil Pemrosesan Gambar")

        central_widget = QWidget(self)
        self.setCentralWidget(central_widget)

        layout = QVBoxLayout()
        self.result_label = QLabel()
        layout.addWidget(self.result_label)

        self.save_button = QPushButton("Simpan")
        layout.addWidget(self.save_button)

        self.close_button = QPushButton("Close")
        layout.addWidget(self.close_button)

        central_widget.setLayout(layout)

        pixmap = QPixmap.fromImage(image)
        self.result_label.setPixmap(pixmap)
        self.result_label.setScaledContents(True)

        self.save_button.clicked.connect(self.save_image)
        self.close_button.clicked.connect(self.close)

        self.image = image  # Simpan referensi ke gambar untuk disimpan
        self.resize(pixmap.width(), pixmap.height())

    def save_image(self):
        pixmap = self.result_label.pixmap()
        if pixmap:
            file_path, _ = QFileDialog.getSaveFileName(None, "Save Image File", "", "Images (*.png *.jpg *.bmp);;All Files (*)")
            if file_path:
                pixmap.save(file_path)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 933)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 701, 391))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 440, 701, 391))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 410, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 840, 111, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(430, 882, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 882, 151, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 890, 151, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Input Gambar 1"))
        self.pushButton_2.setText(_translate("MainWindow", "Input Gambar 2"))
        self.pushButton_3.setText(_translate("MainWindow", "Hasil"))

        self.comboBox.addItem("AND")
        self.comboBox.addItem("OR")
        self.comboBox.addItem("NOT")
        self.comboBox.addItem("Pengurangan")
        self.comboBox.addItem("Penjumlahan")
        self.comboBox.addItem("Perkalian")
        self.comboBox.addItem("Pembagian")
        self.progressBar.setValue(0)
        self.pushButton.clicked.connect(self.browse_image1)
        self.pushButton_2.clicked.connect(self.browse_image2)
        self.pushButton_3.clicked.connect(self.apply_selected_operation)
        self.result_window = None

    def browse_image1(self):
        options = QtWidgets.QFileDialog.Options()
        file_name, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Pilih Gambar 1", "", "Images (*.png *.jpg *.jpeg *.bmp *.gif)", options=options)
        if file_name:
            pixmap = QPixmap(file_name)
            self.label.setPixmap(pixmap)
            self.label.setScaledContents(True)
            self.image1 = pixmap.toImage()

    def browse_image2(self):
        options = QtWidgets.QFileDialog.Options()
        file_name, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Pilih Gambar 2", "", "Images (*.png *.jpg *.jpeg *.bmp *.gif)", options=options)
        if file_name:
            pixmap = QPixmap(file_name)
            self.label_2.setPixmap(pixmap)
            self.label_2.setScaledContents(True)
            self.image2 = pixmap.toImage()

    def apply_selected_operation(self):
        selected_operation = self.comboBox.currentText()

        if selected_operation == "AND":
            self.and_process()
        elif selected_operation == "Perkalian":
            self.kali_process()
        elif selected_operation == "Pembagian":
            self.pembagian_process()
        elif selected_operation == "Pengurangan":
            self.min_process()
        elif selected_operation == "Penjumlahan":
            self.plus_process()
        elif selected_operation == "OR":
            self.or_process()
        elif selected_operation == "NOT":
            self.not_process()

    def show_result_window(self, image):
        self.result_window = ResultWindow(image)
        self.result_window.showFullScreen()  # Menampilkan jendela fullscreen

    def apply_operation(self, operation_func):
        if self.image1 is not None and self.image2 is not None:
            width = min(self.image1.width(), self.image2.width())
            height = min(self.image1.height(), self.image2.height())
            result_image = QImage(width, height, QImage.Format_RGB888)

            total_pixels = width * height
            processed_pixels = 0

            for x in range(width):
                for y in range(height):
                    color1 = QtGui.QColor(self.image1.pixelColor(x, y))
                    color2 = QtGui.QColor(self.image2.pixelColor(x, y))

                    r_result = min(max(operation_func(color1.red(), color2.red()), 0), 255)
                    g_result = min(max(operation_func(color1.green(), color2.green()), 0), 255)
                    b_result = min(max(operation_func(color1.blue(), color2.blue()), 0), 255)
                    r_result = int(r_result)
                    g_result = int(g_result)
                    b_result = int(b_result)
                    result_pixel = QtGui.qRgb(r_result, g_result, b_result)
                    result_image.setPixel(x, y, result_pixel)

                    processed_pixels += 1
                    progress_percent = int((processed_pixels / total_pixels) * 100)
                    self.progressBar.setValue(progress_percent)

            self.show_result_window(result_image)
            self.progressBar.setValue(0)

    def and_process(self):
        self.apply_operation(lambda x, y: x & y)

    def kali_process(self):
        self.apply_operation(lambda x, y: x * y)

    def pembagian_process(self):
        self.apply_operation(lambda x, y: x / max(y, 1))

    def min_process(self):
        self.apply_operation(lambda x, y: max(x - y, 0))

    def plus_process(self):
        self.apply_operation(lambda x, y: min(x + y, 255))

    def or_process(self):
        self.apply_operation(lambda x, y: x | y)

    def not_process(self):
        if self.image1 is not None:
            width = self.image1.width()
            height = self.image1.height()
            result_image = QImage(width, height, QImage.Format_RGB888)

            total_pixels = width * height
            processed_pixels = 0

            for x in range(width):
                for y in range(height):
                    color2 = QtGui.QColor(self.image1.pixelColor(x, y))

                    r_result = 255 - color2.red()
                    g_result = 255 - color2.green()
                    b_result = 255 - color2.blue()

                    result_pixel = QtGui.qRgb(r_result, g_result, b_result)
                    result_image.setPixel(x, y, result_pixel)

                    processed_pixels += 1
                    progress_percent = int((processed_pixels / total_pixels) * 100)
                    self.progressBar.setValue(progress_percent)

            self.show_result_window(result_image)
            self.progressBar.setValue(0)

    def show_result_window(self, image):
        if self.result_window is None:
            self.result_window = ResultWindow(image)
        else:
            self.result_window.result_label.setPixmap(QPixmap.fromImage(image))
        self.result_window.showFullScreen()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    screen = QtWidgets.QApplication.desktop().screenGeometry()
    size = MainWindow.geometry()
    MainWindow.move((screen.width() - size.width()) // 2, (screen.height() - size.height()) // 3)

    sys.exit(app.exec_())